import DoubleHeader from './DoubleHeader';
import Head from 'next/head';

import links from './routes';
import styles from '../styles/Home.module.css';

interface LayoutProps {
	children: React.ReactNode;
	navIndex: number;
}

export default function StdLayout({ children, navIndex }: LayoutProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DoubleHeader
				mainLinks={links.mainLinks}
				userLinks={links.userLinks}
				navIndex={navIndex}
			/>
			<main style={{ position: 'relative', top: '-7.45rem' }}>{children}</main>
			{/* <Footer /> */}
		</>
	);
}
